[package]
name = "deno_runtime_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
deno_runtime = "0.73.0"
deno-bundler = "0.6.0"
tokio = { version = "1", features = ["full"] }

[profile.release]
lto = true
strip = true
debug = false
opt-level = 'z'